---
title: "FInal project"
output: html_document
---

```{r,message=FALSE,warning=FALSE,results='hide',echo=FALSE}
library(readr)
library(ggplot2)
library(ggmap)
library(tmap)
library(sp)
library(DT)
library(devtools)
library(geojsonio)
library(leaflet)
library(usmap)
library(stringr)
library(raster)
library(tidyverse)
# rinc= read_csv("C:/Users/22151/Desktop/Final project/10.csv")
rinc= read_csv("10.csv")
rinc<- rinc[rinc$own_code==0,]
# area<- read_csv("C:/Users/22151/Desktop/Final project/area-titles-csv.csv")
area<- read_csv("area-titles-csv.csv")
# coor<- read_csv("C:/Users/22151/Desktop/Final project/uscounties.csv")
coor<- read_csv("uscounties.csv")
rinc$area_fips<- sub("^0+", "", rinc$area_fips)
allinc<- merge(area,rinc,all.y = TRUE)
allinc$county<- allinc$area_title
allinc[c("county","states")]<- str_split_fixed(allinc$county,',',2)
allinc$county<- sub("County",'',allinc$county)
coor<- coor[,c(1,6,7,8, 9)]
colnames(coor)[2]<- "states"
allinc$states<- sub(" ",'',allinc$states)
allinc$county<- trimws(allinc$county,which = c("both"))
K<- merge(allinc,coor)
K$fips=K$area_fips
```

## R Markdown


```{R,echo=FALSE,message=FALSE,warning=FALSE}
p1<- plot_usmap(regions= "counties",data=K,values="avg_wkly_wage")+
  scale_fill_continuous(
    low = "yellow", high = "red", name = "average weekly wage", label = scales::comma
  ) + theme(legend.position = "right")
p2<- plot_usmap(regions= "counties",data=K,values="oty_avg_wkly_wage_chg")+
  scale_fill_continuous(
    low = "yellow", high = "red", name = "over the year change in average weekly wage", label = scales::comma
  ) + theme(legend.position = "right")
p3<- plot_usmap(regions= "counties",data=K,values="qtrly_estabs")+
  scale_fill_continuous(
    low = "yellow", high = "red", name = "Count of establishments for a given quarter", label = scales::comma
  ) + theme(legend.position = "right")

p4<- plot_usmap(regions= "counties",data=K,values="oty_qtrly_estabs_chg")+
  scale_fill_continuous(
    low = "yellow", high = "red", name = "Over-the-year change in the count of establishments", label = scales::comma
  ) + theme(legend.position = "right")
```

## Including Plots


```{R,echo=FALSE,message=FALSE,warning=FALSE}
p1
```

```{R,echo=FALSE,message=FALSE,warning=FALSE}
p2
```

```{R,echo=FALSE,message=FALSE,warning=FALSE}
p3
```

```{R,echo=FALSE,message=FALSE,warning=FALSE}
p4
```


```{r echo=FALSE,message=FALSE,warning=FALSE}
library(plotly)
p = K %>% group_by(states) %>% 
  summarise(avg=mean(avg_wkly_wage)) %>%
  ggplot(aes(x=reorder(states, avg), y=avg, fill=states)) + geom_col() +
  coord_flip() +
  labs(x="States", y="Average weekly wage",
       title="Average weekly wage by states")
ggplotly(p)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
p <- ggplot(K, aes(x=population, y=avg_wkly_wage)) + geom_point() +
  geom_smooth(method="lm", formula="y~x", se=F) +
  geom_smooth(method="lm", formula=y~poly(x, 2), se=F, color="red") +
  geom_smooth(method="lm", formula=y~poly(x, 3), se=F, color="green") +
  labs(x="Population", y="Average weekly wage",
       title="Average weekly wage vs population")
ggplotly(p)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
p1<- plot_usmap(regions= "counties",data=K,values="avg_wkly_wage")+
  scale_fill_continuous(
    low = "yellow", high = "red", name = "average weekly wage", label = scales::comma
  ) + theme(legend.position = "right")
ggplotly(p1)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
p <- K %>% filter(states  %in% c("Texas", "Iowa", "California",
                                 "Illinois")) %>%
  ggplot(aes(x=states, y=avg_wkly_wage, fill=states)) +
  geom_boxplot(show.legend = F) +
  geom_jitter(alpha=0.5, size=0.5) +
  labs(x="States", y="Average weekly wage",
       title="Distribution of average weekly wages")
ggplotly(p)
```

```{r echo=FALSE,message=FALSE,warning=FALSE}
p <- K %>% filter(states  %in% c("Texas", "Iowa", "California",
                                 "Illinois")) %>%
  ggplot(aes(x=avg_wkly_wage, fill=states)) +
  geom_density(alpha=0.5) +
  labs(x="Average weekly wage",
       title="Density plot of average weekly wages")
ggplotly(p)
```

```{r  echo=FALSE,message=FALSE,warning=FALSE}
library(DT)
datatable(K)
```


